api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
      expire: ${JWT_EXPIRE:9}

server:
  port: 5555
  error:
    include-stacktrace: never

spring:
  application:
    name: 'Desafio DIO'
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
      
logging:
  level:
    root: ${LOG_LEVEL:INFO}

springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui.html